"Search system
"Set character code to UTF-8
set fenc=utf-8
"No create backup files
set nobackup
"No create swap files
set noswapfile
"Automatically reread a file you are editing when it is changed
set autoread
"Allow other files to be opened even if the buffer is being edited
set hidden
"Displays the status of the command being entered
set showcmd


"Visual system
"Display line numbers
set number
"Highlight the current line
set cursorline
"Highlight the current column
set cursorcolumn
"Move the cursor to one character ahead of the end of the line
set virtualedit=onemore
"Indents are smart indents.
set smartindent
"Visualize the beep sound
set visualbell
"Display the corresponding parentheses when entering parentheses
set showmatch
"Always show the status line
set laststatus=2
"Command Line Completion
set wildmode=list:longest
"Moves by display line on wrapping.
nnoremap j gj
nnoremap k gk
"Syntax highlighting enabled
syntax enable


"Tab system
"Visualize Invisible Characters
set list listchars=tab:\▸\-
"Set Tab characters to half-width spaces.
set expandtab
"Display width of Tab characters other than the beginning of a line
set tabstop=2
" Display width of the Tab character at the beginning of a line
set shiftwidth=2


"Search system
"If the search string is in lower case, the search is case-insensitive.
set ignorecase
"If a search string contains uppercase letters, it is searched separately. 
set smartcase
"When entering a search string, the target string is hit sequentially. 
set incsearch
"Go back to the beginning when you reach the end of the search 
set wrapscan
"Highlight the search term 
set hlsearch
"Press the ESC key twice to cancel the highlight. 
nmap <Esc><Esc> :nohlsearch<CR><Esc>


"Plugin install system
"Plugin install by using vim-plug
call plug#begin('~/.vim/plugged') "Specify where to save the plugin in ('').
  "Install dracula colorscheme
  Plug 'dracula/vim', { 'as': 'dracula' }
  "Install snippet
  Plug 'Shougo/neocomplcache'
  Plug 'Shougo/neosnippet.vim'
  Plug 'Shougo/neosnippet-snippets'
  "Install React tools
  Plug 'pangloss/vim-javascript', { 'for': ['javascript', 'javascript.jsx'] }
  Plug 'othree/yajs.vim', { 'for': ['javascript', 'javascript.jsx'] }
  Plug 'othree/es.next.syntax.vim', { 'for': ['javascript', 'javascript.jsx'] }
  Plug 'othree/javascript-libraries-syntax.vim', { 'for': ['javascript', 'javascript.jsx'] }
  Plug 'maxmellon/vim-jsx-pretty', { 'for': ['javascript', 'javascript.jsx'] }
call plug#end()


"To reflect the dracula in vim, add the following to 'call plug#end()'
color dracula
highlight Normal ctermbg=NONE guibg=NONE
highlight NonText ctermbg=NONE guibg=NONE
highlight SpecialKey ctermbg=NONE guibg=NONE
highlight EndOfBuffer ctermbg=NONE guibg=NONE

"Snippets system
"Specify the directory for your own snippet
let g:neosnippet#snippets_directory='~/.vim/bundle/neosnippet-snippets/snippets/ , ~/.vim/snippets'
"Enabling neocomplcache at startup
let g:neocomplcache_enable_at_startup = 1
"Expand the Snippet at insert mode
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
"Expand the Snippet at select mode
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
"Disable snippet preview
set completeopt-=preview
